version: "3.8"

services:
  app:
    build: .
    container_name: 360-viewer
    ports:
      - "3000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
    restart: unless-stopped
